language: node_js
node_js:
  - '8'
  - '10'
  - '12'
dist: xenial
install:
  - apt-get install -y can-utils
  - apt-get install -y nodejs-dev
  - apt-get install -y linux-modules-extra-$(uname -r)
before_script:
  - npm install -g nodeunit
  - npm install
script:
  - sh prepare_test_env.sh
  - NODE_PATH=. nodeunit tests
